# Generated by Django 4.2.4 on 2023-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(null=True, upload_to='Authors/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='Books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_count',
            field=models.IntegerField(default=0),
        ),
    ]
