# Generated by Django 4.2.4 on 2023-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/Authors/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='images/Books/'),
        ),
    ]
