# Generated by Django 4.2.4 on 2023-09-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_author_img_alter_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
