# Generated by Django 4.2.4 on 2023-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.CharField(default='category', max_length=30),
        ),
    ]
