# Generated by Django 4.2.4 on 2023-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
